device key hal initial commit
yossi2le/mbed-os pull request #2
Opened 2018-02-21 09:49 UTC by yossi2le

Notes:
- Pull requests will not be accepted until the submitter has agreed to the [contributer agreement](https://github.com/ARMmbed/mbed-os/blob/master/CONTRIBUTING.md).
- This is just a template, so feel free to use/remove the unnecessary things

## Description

A few sentences describing the overall goals of the pull request's commits.

## Status

**READY/IN DEVELOPMENT/HOLD**

## Migrations

If this PR changes any APIs or behaviors, give a short description of what *API users* should do when this PR is merged.

YES | NO

## Related PRs

List related PRs against other branches:

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos

- [ ] Tests
- [ ] Documentation

## Deploy notes

Notes regarding the deployment of this PR. These should note any required changes in the build environment, tools, compilers and so on.

## Steps to test or reproduce

Outline the steps to test or reproduce the PR here.

2018-02-25 15:58 UTC, dannybenor requested changes

2018-02-25 15:58 UTC, dannybenor commented on hal/device_key_api.h
> + * Copyright (c) 2016 ARM Limited
change the year to 2018

2018-02-25 15:58 UTC, dannybenor commented on hal/device_key_api.h
> +#define DEVICE_KEY_LEN 16   /* DEVICE_KEY key length in bytes */
What is the meaning of this define? Do you mean minimal key length?

2018-02-25 15:58 UTC, dannybenor commented on targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device_key_api.c
> + *  Return the values stored in registers UIDH, UIDMH, UIDML, UIDL. This value is predictable therefore not secure, but used as example
I think the license should be the first text

2018-02-25 15:58 UTC, dannybenor commented on targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device_key_api.c
> + *  Return the values stored in registers UIDH, UIDMH, UIDML, UIDL. This value is predictable therefore not secure, but used as example
Part of this value is the device serial number therefore predictable

2018-02-25 15:58 UTC, dannybenor commented on hal/device_key_api.h
> +#include "fsl_common.h"
I think fsl_common is platform dependent

2018-02-25 16:01 UTC, dannybenor commented on hal/device_key_api.h
> + */
please add a comment that only 16 or 32 are legal return values from device_key_get_size_in_bytes

2018-02-28 09:43 UTC, dannybenor requested changes

2018-02-28 09:43 UTC, dannybenor commented on TESTS/mbed_hal/device_key/main.cpp
> +    size_t len = expected;
Initializing len with expected is not a good idea. Allocate a bigger buffer and pass a size bigger than DEVICE_KEY_32BYTE. What if the implementation does not set the value?

2018-02-28 09:43 UTC, dannybenor commented on TESTS/mbed_hal/device_key/main.cpp
> +        TEST_ASSERT_EQUAL_INT32_ARRAY(buffer1, buffer2, len2 / sizeof(uint32_t));
Please check the the implementation actually wrote something (not the initial zeros)

2018-02-28 16:03 UTC, dannybenor requested changes

2018-02-28 16:03 UTC, dannybenor commented on TESTS/mbed_hal/device_key/main.cpp
> +    bool is_empty = !memcmp(empty_buffer, buffer1, DEVICE_KEY_32BYTE);
You are mixing here int with bool

2018-03-04 16:18 UTC, davidsaada commented on hal/device_key_api.h
> +    DEVICEKEY_HAL_SUCCESS          = 0,
Please add space before 0.

2018-03-04 16:54 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +
Why is this enum? Wouldn't a define or a const be better if you care about the values?

2018-03-04 16:55 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +    size_t len = DEVICE_KEY_16BYTE/2;
Please add space between both sides of a math operand - here it should be `DEVICE_KEY_16BYTE / 2`
(Applies to all following code as well)

2018-03-04 16:56 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +    size_t len = (DEVICE_KEY_32BYTE*2);
Space between both sides of `*`

2018-03-04 16:59 UTC, davidsaada commented on hal/device_key_api.h
> +
Why is `output` defined as `uint32_t *`? Should it be aligned to 4 bytes? I don't think it should.

2018-03-04 16:59 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +    TEST_ASSERT_FALSE(is_empty);
Spaces between both sides of `=`

2018-03-04 17:00 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +    bool is_empty=!memcmp(empty_buffer, buffer1, DEVICE_KEY_32BYTE);
Spaces between both sides of `=`

2018-03-04 17:02 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +    memset(buffer, 0, DEVICE_KEY_32BYTE*2);
It's better to use `sizeof(buffer)` as the size (in case you decide to change the buffer size.

2018-03-04 17:05 UTC, davidsaada commented on hal/device_key_api.h
> +int device_key_get_value(uint32_t *output, size_t *length);
You use the term `size` in previous API and `length` in the second parameter here. Better use the same terms (size is better IMO).

2018-03-04 17:07 UTC, davidsaada commented on targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device_key_api.c
> +
Same comment as before regarding usage of the terms `LEN` and `size`.

2018-03-04 17:08 UTC, davidsaada commented on targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device_key_api.c
> +    unsigned int i;
Is `i` variable used? Need to pay attention to warnings.

2018-03-04 17:09 UTC, davidsaada commented on targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device_key_api.c
> +#include "cmsis.h"
What do you need this include for?

2018-03-04 17:12 UTC, davidsaada commented on TESTS/mbed_hal/device_key/main.cpp
> +            "Device key length is not 16 or 32 Byte long");
Pad with more spaces (should be under `DEVICE_KEY_16BYTE`)

2018-04-11 11:19 UTC, closed without merging