Yossi device key driver
yossi2le/mbed-os pull request #3
Opened 2018-03-08 14:29 UTC by yossi2le

### Description

This pull request is for code review of the DeviceKey driver phase 1.

### Pull request type
- [ ] Feature

2018-03-11 15:02 UTC, dannybenor requested changes

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.h
> +    int device_key_derive_key(const unsigned char *isalt, size_t isalt_size, unsigned char *output, size_t ikey_type);
DeviceKeytype enum, size_t ikey_type, key_type: Balagan!

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.h
> +    int device_key_set_value(uint32_t *value, size_t isize);
Change the name to device_inject_root_of_trust

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.h
> +    int write_key_to_nvstroe(uint32_t *value, size_t isize);
nvstore

2018-03-11 15:02 UTC, dannybenor commented on targets/targets.json
> +        "device_has": ["DEVKEY", "ANALOGIN", "ANALOGOUT", "I2C", "I2CSLAVE", "INTERRUPTIN", "LOWPOWERTIMER", "PORTIN", "PORTINOUT", "PORTOUT", "PWMOUT", "RTC", "SERIAL", "SERIAL_FC", "SERIAL_ASYNCH",
Please undo this change

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +#if !defined(MBEDTLS_CONFIG_FILE)
Don't think you need this include. The configuration of mbedtls can be done in different ways

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +    //First try to read the key form NVStore
comment not in right place

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +    int ret = read_key_from_nvstroe(key_buff, actual_size);
please fix the function name to read_key_from_nvstore

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +    //If the key was not find in NVStore we will create it by using TRNG and then save it to NVStore
found

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +       if (DEVICEKEY_SUCCESS != generate_key_by_trns(key_buff,actual_size)) {
what is trns?

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +           return ret;
ret is not up-to-date. You missed generate_key_by_trns

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +           return ret;
ret is not up-to-date you missed device_key_set_value

2018-03-11 15:02 UTC, dannybenor commented on drivers/DeviceKey.cpp
> +    ret = get_derive_key(key_buff, actual_size, salt, isalt_size, output, ikey_type);
change the name to get_derived_key

2018-03-11 17:29 UTC, davidsaada requested changes

2018-03-11 17:29 UTC, davidsaada commented on TESTS/mbed_drivers/device_key/main.cpp
> +    memcpy((void*)key,(const void*)"1234567812345678",16);
Why do you need these casts? Should work without them as well.

2018-03-11 17:29 UTC, davidsaada commented on TESTS/mbed_drivers/device_key/main.cpp
> +    memcpy((void*)key,(const void*)"1234567812345678",16);
Spaces between arguments.

2018-03-11 17:29 UTC, davidsaada commented on TESTS/mbed_drivers/device_key/main.cpp
> +    int size=16;
Spaces

2018-03-11 17:29 UTC, davidsaada commented on TESTS/mbed_drivers/device_key/main.cpp
> +    nvstore.init();
init is redundant if reset is called right after.

2018-03-11 17:29 UTC, davidsaada commented on TESTS/mbed_drivers/device_key/main.cpp
> +    unsigned char salt[] = { "The quick brown fox jumps over the lazy dog" };
String initialization in this module is not uniform - once with braces, once without. Maybe it's better to lose the braces.

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    ret = get_derive_key(key_buff, actual_size, salt, isalt_size, output, ikey_type);
You forgot to rename it to get_derived_key

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    mbedtls_cipher_type_t mbedtls_cipher_type=MBEDTLS_CIPHER_AES_128_ECB;
spaces

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +        mbedtls_cipher_type=MBEDTLS_CIPHER_AES_256_ECB;
spaces

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +        ret = this->calc_cmac(isalt, isalt_size, ikey_buff, ikey_size, output);
`this` is redundant. calling a member function is always on `this`.

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    memcpy((void*)ikey_buff,(const void*)"1234567812345678",16);
Same here - why the casts?
Spaces as well.

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.h
> +
Do both these defines need to be in the header file (I suspect not)? If they do, limit the scope by adding a prefix to their names.

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.h
> +class DeviceKey {
If it's a singleton class, it should definitely be non copyable. Derive it from NonCopyable (see NVStore class for reference).

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +#include <nvstore.h>
Use quotes here.

2018-03-11 17:29 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    int nvStatus = nvstore.get(NVSTORE_KEY_ROT, short_size, output, short_size);
Using the same argument for buffer size and returned size parameters is a very bad idea. Please define an additional variable for it (also applies to all other get instances).

2018-03-13 12:25 UTC, davidsaada requested changes

2018-03-13 12:25 UTC, davidsaada commented on TESTS/mbed_drivers/device_key/main.cpp
> +Case cases[] = { Case("Device Key - inject value wrong size"            , device_inject_root_of_trust_wrong_size_test        , greentea_failure_handler),
Brace should be in a separate line

2018-03-13 12:25 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    if (DEVICE_KEY_16BYTE != ikey_type && DEVICE_KEY_32BYTE != ikey_type){
Space before the brace

2018-03-13 12:25 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    if(DEVICE_KEY_16BYTE != actual_size && DEVICE_KEY_32BYTE != actual_size) {
Space between if and parentheses (search, there are a few of these)

2018-03-13 12:34 UTC, davidsaada approved these changes

2018-03-21 13:38 UTC, davidsaada requested changes

2018-03-21 13:38 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +//This constant is temporary because NVStroe do not support keys enum yet.
NVStore

2018-03-21 13:38 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +        double_size_salt = new unsigned char[isalt_size * 2];
You don't free this in case of success.

2018-03-21 13:38 UTC, davidsaada commented on drivers/DeviceKey.cpp
> +    if ( DEVICEKEY_SUCCESS != ret || in_size != size) {
redundant space

2018-03-21 13:38 UTC, davidsaada commented on drivers/DeviceKey.h
> +
Need to enclose this class with Doxygen comments. See nvstore.h for reference.

2018-03-21 14:51 UTC, davidsaada approved these changes

2018-04-11 11:19 UTC, closed without merging