Refactoring in kv_config, Add remarks documentation to kv_config and remove rbp_num_of_enteries
yossi2le/mbed-os pull request #8
Opened 2018-12-31 09:56 UTC by yossi2le

### Description

The function _get_blockdevice_FLASHIAP in kv_config.cpp has been refactored into 3 function. the first function will calculate the default start address and size for internal TDBStore in case of rbp when KVStore is configured as TDB_EXTERNAL or FILESYSTEM. a second function will calculate the default start address and size for the case we run in TDB_INTERNAL. and the last is _get_blockdevice_FLASHIAP which will check the validity of parameters and create the block device.

Also, lots of remarks have been added to the code in order to simplify the understanding of the complex configuration code.

Last thing, the parameter of rbp_num_of_enteries has been remove from TDB_EXTERNAl and FILESYSTEM configuration files.

### Pull request type 

    [ ] Fix
    [ ] Refactor
    [ ] Target update
    [ ] Functionality change
    [ ] Docs update
    [ ] Test update
    [x] Breaking change

### Reviewers

@dannybenor , @davidsaada , @theamirocohen and @offirko 
Please review. I will create a real PR after your review.

2018-12-31 10:26 UTC, davidsaada requested changes
Looks good, excluding some minor English fixes.

2018-12-31 10:26 UTC, davidsaada commented on features/storage/kvstore/conf/filesystem/mbed_lib.json
> +            "help": "If default the size will be the 2 last sector of internal flash",
If you already changed it, please change to "Default is the size of the 2 last sectors of internal flash".

2018-12-31 10:26 UTC, davidsaada commented on features/storage/kvstore/conf/kv_config.cpp
> +        tr_warning("KV Config: there is less than 2 sector TDBStore will not work.");
"There are less than two sectors - TDBStore will not work."

2018-12-31 10:26 UTC, davidsaada commented on features/storage/kvstore/conf/tdb_external/mbed_lib.json
> +            "help": "If default the size will be the 2 last sector of internal flash",
Same here - "Default is the size of the 2 last sectors of internal flash".

2018-12-31 12:55 UTC, yossi2le commented on features/storage/kvstore/conf/filesystem/mbed_lib.json
> +            "help": "If default the size will be the 2 last sector of internal flash",
fixed

2018-12-31 12:55 UTC, yossi2le commented on features/storage/kvstore/conf/kv_config.cpp
> +        tr_warning("KV Config: there is less than 2 sector TDBStore will not work.");
fixed

2018-12-31 12:55 UTC, yossi2le commented on features/storage/kvstore/conf/tdb_external/mbed_lib.json
> +            "help": "If default the size will be the 2 last sector of internal flash",
fixed

2019-01-03 07:25 UTC, offirko commented on features/storage/kvstore/conf/kv_config.cpp
> +    if (size == 0) {
I dont think size can be 0 here because its Non default configuration and here start_address==0, so size must be different. 
If for any reason size is 0 , then when you calculate above:
    _start_address = flash_end_address - size;
    aligned_start_address = align_down(start_address, flash.get_sector_size(start_address));_

start_address will become flash_end_address and then
I think it should be flash.get_sector_size(start_address-1)

2019-01-03 14:19 UTC, closed without merging